server:
  port: 8083
  servlet:
    context-path: /reviews
spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: "jdbc:mysql://localhost:3306/review_service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG

